#
# Module manifest for module 'TFVC.PowerShell'
#
# Generated by: Cory Stein
#
# Generated on: 10/14/2016
#

@{

# Script module or binary module file associated with this manifest.
RootModule = '.\TFVC.PowerShell.dll'

# Version number of this module.
ModuleVersion = '1.0.0.0'

# ID used to uniquely identify this module
GUID = 'fad2ffc8-3504-48ef-8d4d-a85967250108'

# Author of this module
Author = 'Cory Stein'

# Company or vendor of this module
#CompanyName = 'N/A'

# Copyright statement for this module
Copyright = '(c) 2016 Cory Stein. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Provides additional Cmdlets for automating PwC GATT tasks'

# Minimum version of the Windows PowerShell engine required by this module
# PowerShellVersion = ''

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
#FormatsToProcess = @('SPOCmdlets.Format.ps1xml')

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
#NestedModules = @('PowerShell.Common.psd1', 'PowerShell.Common.Azure.psd1')

# Functions to export from this module
FunctionsToExport = '*'

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess
# PrivateData = ''
	
# HelpInfo URI of this module
HelpInfoURI = '.\TFVC.PowerShell.dll-Help.xml'

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}
